import type { PanelResult } from "@/lib/agents/panel";

// Rendered hidden on screen; shown only when printing (see .print-report in
// globals.css). This is the clean PDF layout the user downloads.
export function ReportPrint({
  visaName,
  visaFullName,
  panel,
  letter,
}: {
  visaName: string;
  visaFullName: string;
  panel: PanelResult;
  letter: string | null;
}) {
  const VERDICT_LABEL: Record<string, string> = {
    met: "MET",
    partial: "PARTIAL",
    gap: "GAP",
  };

  return (
    <div className="print-report" style={{ color: "#111", fontSize: "12px", lineHeight: 1.5 }}>
      <div style={{ borderBottom: "2px solid #111", paddingBottom: 8, marginBottom: 16 }}>
        <div style={{ fontSize: "18px", fontWeight: 600 }}>
          Caliber — {visaName} readiness assessment
        </div>
        <div style={{ color: "#555" }}>{visaFullName}</div>
      </div>

      <div style={{ marginBottom: 16 }}>
        <div style={{ fontSize: "22px", fontWeight: 600 }}>
          {panel.metCount} / {panel.total} criteria met —{" "}
          {panel.eligible ? "Likely eligible" : "Not yet eligible"}
        </div>
        <div style={{ color: "#333" }}>{panel.summary}</div>
      </div>

      <div style={{ fontWeight: 600, marginBottom: 6 }}>Criteria breakdown</div>
      {panel.criteria.map((c) => (
        <div key={c.criterionId} style={{ marginBottom: 12, breakInside: "avoid" }}>
          <div style={{ fontWeight: 600 }}>
            [{VERDICT_LABEL[c.verdict]}] {c.label}{" "}
            <span style={{ fontWeight: 400, color: "#777" }}>
              ({c.confidence} confidence)
            </span>
          </div>
          <div style={{ margin: "2px 0" }}>
            <b>Advocate:</b> {c.advocate}
          </div>
          <div style={{ margin: "2px 0" }}>
            <b>Examiner (likely RFE):</b> {c.examiner}
          </div>
          <div style={{ margin: "2px 0" }}>
            <b>Adjudicator:</b> {c.reasoning}
          </div>
          {c.verdict !== "met" && c.runway && (
            <div style={{ margin: "2px 0" }}>
              <b>How to close this:</b> {c.runway}
            </div>
          )}
        </div>
      ))}

      {letter && (
        <div style={{ marginTop: 20, breakBefore: "page" }}>
          <div style={{ fontWeight: 600, marginBottom: 6 }}>
            Draft petition argument
          </div>
          <div style={{ whiteSpace: "pre-wrap" }}>{letter}</div>
        </div>
      )}

      <div style={{ marginTop: 24, borderTop: "1px solid #ccc", paddingTop: 8, color: "#777", fontSize: "10px" }}>
        Generated by Caliber. Informational self-assessment only — not legal
        advice, and not a substitute for a licensed immigration attorney.
      </div>
    </div>
  );
}
